### ISSUE TITLE
Try to identify images of celebrities and show a count for them

### ISSUE THREAD

**Issue by simonw** [simonw/laion-aesthetic-datasette#5]
Would be very interesting to see how many images in the data correspond to popular celebrities.

Running full term extraction (ala https://simonwillison.net/2022/Jul/11/sqlite-comprehend/) would be way too expensive for 52m rows.

Could try using something like spaCy, but my hunch is that given a good list of celebrity names just running dumb FTS searches and counting the results would be good enough.

**Comment by cavallarilopezcarla-web** [comment]
![Image](https://github.com/user-attachments/assets/0c3ec0b1-4d74-4a1e-b386-fd4963e933d4)
